# Generated by Django 4.0.1 on 2022-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
